[package]
name = "nynaeve"
version = "0.0.1"
authors = ["Enrico Lovisotto <enricolovisotto@gmail.com>"]

[dependencies]
postgres = {version = "0.14", features = ["with-chrono"]}
chrono = "0.3.1"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
